<template>
  <div class="LoadingScreen">

    <div class="loadingio-spinner-spinner-f3y7mcyjft">
      <div class="ldio-8oeaqtfxi3l">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">

export default {
  name: "LoadingScreen",
  props: {}
}
</script>

<style lang="scss" scoped>
.LoadingScreen {
  position: fixed;
  inset: 0;
  background-color: rgba(24, 25, 34, 0.70);
  backdrop-filter: blur(8px);
  z-index: 9999;
  font-size: 20px;
  font-weight: 600;
  color: white;

  display: flex;
  justify-content: center;
  align-items: center;
}


@keyframes ldio-8oeaqtfxi3l {
  0% {
    opacity: 1
  }
  100% {
    opacity: 0
  }
}

.ldio-8oeaqtfxi3l div {
  left: 48px;
  top: 25px;
  position: absolute;
  animation: ldio-8oeaqtfxi3l linear 1s infinite;
  background: white;
  width: 4px;
  height: 10px;
  border-radius: 1.4000000000000001px / 1.4000000000000001px;
  transform-origin: 2px 25px;
}

.ldio-8oeaqtfxi3l div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9333333333333333s;
  background: white;
}

.ldio-8oeaqtfxi3l div:nth-child(2) {
  transform: rotate(24deg);
  animation-delay: -0.8666666666666667s;
  background: white;
}

.ldio-8oeaqtfxi3l div:nth-child(3) {
  transform: rotate(48deg);
  animation-delay: -0.8s;
  background: white;
}

.ldio-8oeaqtfxi3l div:nth-child(4) {
  transform: rotate(72deg);
  animation-delay: -0.7333333333333333s;
  background: white;
}

.ldio-8oeaqtfxi3l div:nth-child(5) {
  transform: rotate(96deg);
  animation-delay: -0.6666666666666666s;
  background: white;
}

.ldio-8oeaqtfxi3l div:nth-child(6) {
  transform: rotate(120deg);
  animation-delay: -0.6s;
  background: white;
}

.ldio-8oeaqtfxi3l div:nth-child(7) {
  transform: rotate(144deg);
  animation-delay: -0.5333333333333333s;
  background: white;
}

.ldio-8oeaqtfxi3l div:nth-child(8) {
  transform: rotate(168deg);
  animation-delay: -0.4666666666666667s;
  background: white;
}

.ldio-8oeaqtfxi3l div:nth-child(9) {
  transform: rotate(192deg);
  animation-delay: -0.4s;
  background: white;
}

.ldio-8oeaqtfxi3l div:nth-child(10) {
  transform: rotate(216deg);
  animation-delay: -0.3333333333333333s;
  background: white;
}

.ldio-8oeaqtfxi3l div:nth-child(11) {
  transform: rotate(240deg);
  animation-delay: -0.26666666666666666s;
  background: white;
}

.ldio-8oeaqtfxi3l div:nth-child(12) {
  transform: rotate(264deg);
  animation-delay: -0.2s;
  background: white;
}

.ldio-8oeaqtfxi3l div:nth-child(13) {
  transform: rotate(288deg);
  animation-delay: -0.13333333333333333s;
  background: white;
}

.ldio-8oeaqtfxi3l div:nth-child(14) {
  transform: rotate(312deg);
  animation-delay: -0.06666666666666667s;
  background: white;
}

.ldio-8oeaqtfxi3l div:nth-child(15) {
  transform: rotate(336deg);
  animation-delay: 0s;
  background: white;
}

.loadingio-spinner-spinner-f3y7mcyjft {
  width: 61px;
  height: 61px;
  display: inline-block;
  overflow: hidden;
  background: transparent;
}

.ldio-8oeaqtfxi3l {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.61);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}

.ldio-8oeaqtfxi3l div {
  box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>